#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define BLOCK_SIZE 34
#define NB_BLOCKS_WIDTH 12
#define NB_BLOCKS_HEIGHT 12
#define WIDTH_WINDOW BLOCK_SIZE * NB_BLOCKS_WIDTH
#define HEIGHT_WINDOW BLOCK_SIZE * NB_BLOCKS_HEIGHT
#define TITLE "My First 2D Game"

enum MOVEMENT { UP, DOWN, LEFT, RIGHT };
enum BLOCK_TYPE { EMPTY, WALL, BOX, GOAL, PLAYER };

#endif // CONSTANTS_H_INCLUDED
